---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/roadmaps":
    get:
      summary: list roadmaps
      responses:
        '200':
          description: successful
    post:
      summary: create roadmap
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                year:
                  type: integer
                quarter:
                  type: integer
              required:
              - title
              - year
              - quarter
  "/api/v1/roadmaps/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show roadmap
      responses:
        '200':
          description: successful
    put:
      summary: update roadmap
      responses:
        '200':
          description: successful
    delete:
      summary: delete roadmap
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
